### ISSUE TITLE
Getting deployment status

### ISSUE THREAD

**Issue by pietermees** [spotinst/spotinst-sdk-nodejs#2]
Is it possible to request the deployment status of a group? i.e. in progress, done, failed ...

**Comment by snir102002** [comment]
Hi @pietermees,
At the moment we don't support roll actions in this SDK but i'm going to create a feature request so you can expect it by the end of next week

**Comment by liranp** [comment]
Hi @pietermees,

We added support for deployment actions. Please find an example [here](https://github.com/spotinst/spotinst-sdk-nodejs/blob/master/examples/aws_group.js#L27-L45).

**Comment by liranp** [comment]
Hi @pietermees,

We added support for deployment actions. Please find an example [here](https://github.com/spotinst/spotinst-sdk-nodejs/blob/master/examples/aws_group.js#L27-L45).

**Comment by pietermees** [comment]
@liranp is there also a way to get the deployment details like you can see them in console?
`/aws/ec2/group/${groupId}/deployment/${rollId}/details`
